name: Build & Push backend to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - "text2sql-backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/lily3130/text2sql-backend   # ← 固定到你的帳號

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # ← 用觸發 workflow 的帳號登入
          password: ${{ secrets.GHCR_TOKEN }}  # ← 需有 packages:write

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./text2sql-backend
          file: ./text2sql-backend/Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
